language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  - pecl channel-update pecl.php.net
  - yes | pecl install imagick

install: composer install

script: vendor/bin/phpunit --verbose
