on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3']
    steps:
      - uses: actions/checkout@master
      - run: sudo apt-get install php${{ matrix.php }}-imagick
      - run: php${{ matrix.php }} -m
      - run: composer install
      - run: php${{ matrix.php }} vendor/bin/phpunit --verbose
