on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: sudo apt-get install php-imagick
      - uses: docker://composer:latest install --ignore-platform-reqs
        with:
          args: --volume .:/app
      - run: vendor/bin/phpunit
