on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3']
    steps:
      - uses: actions/checkout@master
      - run: composer install --ignore-platform-reqs
      - run: php${{ matrix.php }} --version
