name: Continuous integration
on: push
jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.1', '7.2', '7.3']
    steps:
      - uses: actions/checkout@master
      - name: Install required PHP extensions
        run: sudo apt-get install php${{ matrix.php }}-imagick
      - name: Install Composer dependencies
        run: composer install
      - name: Run unit tests
        run: php${{ matrix.php }} vendor/bin/phpunit --verbose
      - name: Check coding style
        run: php${{ matrix.php }} vendor/bin/phpcs --standard=PSR12 src/
